---

- name: Add Virtual Box repo
  become: yes
  lineinfile:
    path: /etc/apt/sources.list
    regexp: 'virtualbox'
    line: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ distro_release }} contrib"

- name: Add Virtual Box repo key
  become: yes
  apt_key:
    url: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"


- name: Install Virtual Box
  become: yes
  apt:
    update_cache: yes
    name: "virtualbox-6.1"

# - name: Download Virtualbox Extension Pack
#   get_url:
#     url: https://download.virtualbox.org/virtualbox/{{ virtualbox_version }}/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version }}.vbox-extpack
#     dest: /tmp/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version }}.vbox-extpack

  # You need to run this manually, because you need to press Y and Enter to confirm...
    #- name: Install Virtualbox Extension Pack
  #  shell: VBoxManage extpack install Oracle_VM_VirtualBox_Extension_Pack-6.1.8.vbox-extpack
  #  become: yes
  #  become_user: root