---

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Add ansible repo
  apt_repository:
    repo: ppa:ansible/ansible

- name: Add diff-so-fancy repo
  apt_repository:
    repo: ppa:aos1/diff-so-fancy

- name: Install packages
  apt:
    name: "{{ applications }}"

# - name: Create new users
#   include_role:
#     name: new-users

- name: Install git
  include_role:
    name: git-install
  vars:
    logins: "{{ users }}"

- name: Install virtualbox
  include_role:
    name: virtualbox-install

- name: Install btop
  include_role:
    name: btop-install

- name: Install dust
  include_role:
    name: dust-install

- name: Install Golang
  include_role:
    name: golang-install

- name: Install fonts
  include_role:
    name: fonts-install

- name: Install Oh-My-ZSH
  include_role:
    name: oh-my-zsh-install

- name: Install neovim
  include_role:
    name: neovim-install